

def print_menu(galaxy_name):
    print(f'\n Welcome! Please select an option for {galaxy_name} from the menu:\n')
    print(' Plot options (use when plot window is active):')
    print('-'*30)
    print('  left-mouse-click:    adjust disk M/L')
    print('  middle-mouse-click:  adjust bulge M/L*')
    print('  right-mouse-click:   adjust halo fit parameters R_C & V_H')
    print('  e:                   toggle +/- 0.1 M/L error bands on/off')
    print('  h:                   re-fit halo using current M/L')
    print('  m:                   mouse-click scaling enabled')
    print('                       (default, interactive mode)')
    print('  n:                   no mouse-click scaling')
    print('                       (label mode activated)')
    print('  c:                   center selected label**')
    print('  d or down arrow:     shift selected label down**')
    print('  l or left arrow:     shift selected label to the left**')
    print('  r or right arrow:    shift selected label to the right**')
    print('  u or up arrow:       shift selected label up**\n')
    print(' Command line options')
    print('-'*30)
    print(' Fit options:')
    print('  f:                   provide fixed M/L and re-fit halo')
    print('  r:                   re-fit halo & M/L using non-linear')
    print('                       least-squares method')
    print(' Save options:')
    print('  p:                   save figure to file')
    print('  s:                   write rotation curves and fit')
    print('                       parameters to text file')
    print('  q:                   quit\n')
    print(' *Middle-mouse-click alternative: "shift + left-mouse-click"\n')
    print(' **Select label text by clicking on it. Be sure to enter')
    print('   label mode first by pressing "n".\n')
    print(' NOTE: You may have to click on the figure after pressing')
    print('       "e" to toggle off the error bands. This is a known')
    print('       issue for some operating systems (Linux).\n')


def print_fit_results(halo_fit_params):
    print('=' * 40)
    print(f'\n Current halo fit parameters:\n')
    print(f" Disk M/L =            {halo_fit_params['d_ml']:.1f}")
    print(f" Bulge M/L =           {halo_fit_params['b_ml']:.1f}")
    print(f" V_H =                 {halo_fit_params['v_h']:.0f} +/- {halo_fit_params['v_h_err']:.0f} km/s")
    print(f" R_C =                 {halo_fit_params['r_c']:.2f} +/- {halo_fit_params['r_c_err']:.2f} kpc")
    print(f" chi squared =         {halo_fit_params['chi_sq']:.3f}")
    print(f" reduced chi squared = {halo_fit_params['red_chi_sq']:.3f}\n")